ML_UNUSUAL_TRANSACTION_RULE_ID = "ml_unusual_transaction"
ML_SPENDING_FORECAST_RULE_ID = "ml_spending_forecast"
ML_SPENDING_FORECAST_RISK_RULE_ID = "ml_spending_forecast_risk"
ML_BUDGET_RECOMMENDATION_RULE_ID = "ml_budget_recommendation"

ML_INSIGHT_RULE_IDS = (
    ML_UNUSUAL_TRANSACTION_RULE_ID,
    ML_SPENDING_FORECAST_RULE_ID,
    ML_SPENDING_FORECAST_RISK_RULE_ID,
    ML_BUDGET_RECOMMENDATION_RULE_ID,
)
